name: Job Rotator Automation

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:       # allows manual run

jobs:
  rotate-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up jq + curl
        run: sudo apt-get install -y jq curl

      - name: Run job rotator script
        run: |
          chmod +x job_rotator.sh
          ./job_rotator.sh

      - name: Commit job_results.log
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add job_results.log
          git commit -m "🔄 Auto-update job results" || echo "No changes to commit"
          git push